import { Suspense } from "react";
import Loading from "../san-pham/[type]/loading";
import "../globals.css";
import "@/styles/scss/nextjs-material-kit.scss?v=1.2.0";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <Suspense fallback={<Loading />}>
      <div>{children}</div>
    </Suspense>
  );
}
