import "../globals.css";
import "@/styles/scss/nextjs-material-kit.scss?v=1.2.0";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return <div>{children}</div>;
}
