import Footer from "@/components/Footer/Footer";
import "./globals.css";
import { Inter } from "next/font/google";
import "@/styles/scss/nextjs-material-kit.scss?v=1.2.0";
import ProductsCartProvider from "@/store/products-cart-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-white">
          <ProductsCartProvider>
            <div className="min-h-[1000px]">{children}</div>
            <Footer />
          </ProductsCartProvider>
        </div>
      </body>
    </html>
  );
}
